apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: dev # change to your namespace(s)

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-deployer
  namespace: dev # change to your namespace(s)
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-deployer
  namespace: dev # change to your namespace(s)
subjects:
- kind: ServiceAccount
  name: ci-deployer
  namespace: dev # change to your namespace(s)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-deployer
