name: deploy
on:
  # Automatic deployments on every new release
  release:
    types:
      - 'published'
  # Manual deployment
  workflow_dispatch:
    inputs:
      deployment:
        description: 'Deployment name'
        required: true
        default: 'echo-server'
      namespace:
        description: 'Kubernetes namespace to deploy into'
        required: true
        default: 'dev'
      version:
        description: 'Specific application version to deploy (used as image tag)'
        required: false
        default: ''
jobs:
  deploy:
    name: run deployment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Deploy chart
      - name: Helm chart deployment
        uses: bryk-io/chart-deploy-action@v1.2.0
        with:
          name: ${{ github.event.inputs.deployment || 'echo-server' }}
          namespace: ${{ github.event.inputs.namespace || 'dev' }}
          version: ${{ github.event.inputs.version }}
        env:
          # Use the name space as prefix to load the required secrets
          KUBECTL_CONFIG: ${{ secrets[format('kubectl_config_{0}', github.event.inputs.namespace)] }}
          CHART_VALUES: ${{ secrets[format('chart_values_{0}', github.event.inputs.namespace)] }}